### ISSUE TITLE
Project will not build with Eclipse

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#14]
At least for me, I'm back to having to use Gradle to build. This is probably my fault, I'll look into it.

**Comment by jasoncarrete5** [comment]
You cannot run a libgdx application as a Java Application from eclipse because it does not properly link the assets directory to the internal file handle. You must run it as a Gradle Project.

###### Error caused by running as a Java Application
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: player.png
	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:144)
	at com.fwumdesoft.project8.Renderer.<init>(Renderer.java:48)
	at com.fwumdesoft.project8.Project8.create(Project8.java:44)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

`Gdx.files.internal("").file().getAbsolutePath();` will not return the path to the assets directory when run as a Java Application.
